import prisma from '../utils/prisma';

/**
 * 将站点页素材写入数据库；带图记录使用 seed 阶段从公网 URL 拉取的 JPEG 二进制（见 remoteMedia.ts）。
 */
export async function seedSiteAssets(imageBuffers: Buffer[]): Promise<void> {
  if (imageBuffers.length === 0) {
    throw new Error('seedSiteAssets: imageBuffers must not be empty');
  }
  await prisma.siteAsset.deleteMany({});

  let imgIdx = 0;

  const items: Array<{
    page: string;
    groupKey: string;
    sortOrder: number;
    title: string | null;
    alt: string | null;
    content?: string | null;
    meta?: string | null;
    withImage: boolean;
    videoUrl: string | null;
  }> = [
    {
      page: 'home',
      groupKey: 'hero_video',
      sortOrder: 0,
      title: null,
      alt: null,
      withImage: false,
      videoUrl: 'https://scrollyvideo.js.org/goldengate.mp4',
    },
    {
      page: 'home',
      groupKey: 'gallery_copy',
      sortOrder: 0,
      title: '红木古韵 传承利好',
      alt: null,
      content:
        '张家港作为中国红木产业的重要基地，凭借得天独厚的地理位置和丰富的木材资源， 已经成为全国最大的红木家具生产和销售中心之一。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'top_gallery',
      sortOrder: 0,
      title: null,
      alt: '红木原材料',
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'top_gallery',
      sortOrder: 1,
      title: null,
      alt: '红木细节',
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'top_gallery',
      sortOrder: 2,
      title: null,
      alt: '红木工厂',
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'stats_intro',
      sortOrder: 0,
      title: '深受行业领导者信赖',
      alt: null,
      content:
        '林之源为众多行业提供可靠的红木解决方案，从高端家具到工艺品制造等，助力客户获得竞争优势。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'stats_metric',
      sortOrder: 0,
      title: '客户',
      alt: null,
      meta: JSON.stringify({
        value: 10000,
        color: 'var(--app-accent-cinnabar)',
      }),
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'stats_metric',
      sortOrder: 1,
      title: '产品系列',
      alt: null,
      meta: JSON.stringify({
        value: 60,
        color: 'var(--app-accent-cinnabar)',
      }),
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'stats_metric',
      sortOrder: 2,
      title: '销售地区',
      alt: null,
      meta: JSON.stringify({
        value: 150,
        color: 'var(--app-accent-cinnabar)',
      }),
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'stats_metric',
      sortOrder: 3,
      title: '年销量',
      alt: null,
      meta: JSON.stringify({
        value: 1000000,
        color: 'var(--app-accent-cinnabar)',
      }),
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'value_copy',
      sortOrder: 0,
      title: '传承红木文化，创新工艺技术',
      alt: null,
      content:
        '我们致力于传承和发扬红木文化，结合现代工艺技术， 打造出既有传统韵味又符合现代审美的红木产品。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'value_proposition',
      sortOrder: 0,
      title: null,
      alt: '红木风景',
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'product_categories',
      sortOrder: 0,
      title: '红木家具',
      alt: '红木家具',
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'product_categories',
      sortOrder: 1,
      title: '红木饰品',
      alt: '红木饰品',
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'product_categories',
      sortOrder: 2,
      title: '红木工艺',
      alt: '红木工艺',
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'product_categories',
      sortOrder: 3,
      title: '红木定制',
      alt: '红木定制',
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'heritage_copy',
      sortOrder: 0,
      title: '匠心工艺，传承百年',
      alt: null,
      content:
        '我们拥有一支技艺精湛的工匠团队， 传承百年红木工艺，每一件产品都凝聚了匠人的心血和智慧。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'cta_copy',
      sortOrder: 0,
      title: '懂红木才会爱上红木',
      alt: null,
      content:
        '我们邀请您深入了解红木文化，感受红木的独特魅力， 选择最适合您的红木产品。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'heritage',
      sortOrder: 0,
      title: null,
      alt: '红木细节',
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'heritage',
      sortOrder: 1,
      title: null,
      alt: '红木细节',
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'home',
      groupKey: 'heritage',
      sortOrder: 2,
      title: null,
      alt: '红木细节',
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'intro',
      sortOrder: 0,
      title: null,
      alt: '公司简介',
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'company_profile',
      sortOrder: 0,
      title: null,
      alt: null,
      content:
        '我们是一家专业从事红木家具设计、生产和销售的企业，拥有多年的行业经验和丰富的专业知识。公司致力于将传统红木工艺与现代设计理念相结合，打造出既具有传统韵味又符合现代生活需求的高品质红木产品。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'company_profile',
      sortOrder: 1,
      title: null,
      alt: null,
      content:
        '我们坚持选用优质的红木材料，采用传统的榫卯结构和精湛的雕刻工艺，确保每一件产品都具有卓越的品质和独特的艺术价值。同时，我们也注重环保理念，所有产品均符合国家环保标准，让客户使用更加放心。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'company_profile',
      sortOrder: 2,
      title: null,
      alt: null,
      content:
        '公司拥有一支专业的设计团队和生产团队，能够根据客户的需求提供定制化服务，满足不同客户的个性化需求。我们的产品涵盖了家具、工艺品、装修材料等多个领域，广泛应用于家庭、酒店、办公场所等各种场景。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'advantage',
      sortOrder: 0,
      title: '优质材料',
      alt: null,
      content: '选用优质的红木材料，确保产品的品质和耐用性。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'advantage',
      sortOrder: 1,
      title: '精湛工艺',
      alt: null,
      content: '采用传统的榫卯结构和精湛的雕刻工艺，确保产品的艺术性和实用性。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'advantage',
      sortOrder: 2,
      title: '专业设计',
      alt: null,
      content: '专业的设计团队，能够根据客户需求提供定制化服务。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'advantage',
      sortOrder: 3,
      title: '环保理念',
      alt: null,
      content: '所有产品均符合国家环保标准，让客户使用更加放心。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'advantage',
      sortOrder: 4,
      title: '完善服务',
      alt: null,
      content: '提供从设计、生产到安装的一站式服务，确保客户满意度。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'advantage',
      sortOrder: 5,
      title: '品牌信誉',
      alt: null,
      content: '多年的行业经验和良好的品牌信誉，值得客户信赖。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'history',
      sortOrder: 0,
      title: '2018 · 公司成立',
      alt: null,
      content: '公司正式成立，专注于红木家具的设计和生产。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'history',
      sortOrder: 1,
      title: '2019 · 扩大生产规模',
      alt: null,
      content: '扩大生产规模，引进先进的生产设备和技术。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'history',
      sortOrder: 2,
      title: '2020 · 产品升级',
      alt: null,
      content: '推出全新系列产品，受到市场广泛好评。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'history',
      sortOrder: 3,
      title: '2021 · 品牌建设',
      alt: null,
      content: '加强品牌建设，提高品牌知名度和影响力。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'history',
      sortOrder: 4,
      title: '2022 · 拓展市场',
      alt: null,
      content: '拓展国内外市场，建立广泛的销售网络。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'history',
      sortOrder: 5,
      title: '2023 · 技术创新',
      alt: null,
      content: '加大技术创新力度，推出更多具有创新性的产品。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'about',
      groupKey: 'history',
      sortOrder: 6,
      title: '2024 · 持续发展',
      alt: null,
      content: '持续发展，不断提升产品品质和服务水平。',
      withImage: false,
      videoUrl: null,
    },
    {
      page: 'case',
      groupKey: 'case_item',
      sortOrder: 0,
      title: '高端红木家具定制项目',
      alt: '高端红木家具定制项目',
      content:
        '为某知名企业定制了一系列高端红木家具，包括会议桌、办公椅、展示柜等。项目采用了优质的红木材料，结合现代设计理念，打造出既具有传统韵味又符合现代办公需求的家具产品。',
      meta: JSON.stringify({
        client: '某知名企业',
        category: '家具定制',
        date: '2024-10-15',
        tags: ['高端定制', '办公家具', '红木'],
      }),
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'case',
      groupKey: 'case_item',
      sortOrder: 1,
      title: '别墅红木装修工程',
      alt: '别墅红木装修工程',
      content:
        '为一栋豪华别墅提供了全套红木装修解决方案，包括地板、楼梯、门窗、家具等。项目注重细节处理，将传统红木工艺与现代装修技术相结合，营造出温馨舒适的居住环境。',
      meta: JSON.stringify({
        client: '私人客户',
        category: '装修工程',
        date: '2024-09-20',
        tags: ['别墅装修', '全屋定制', '传统工艺'],
      }),
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'case',
      groupKey: 'case_item',
      sortOrder: 2,
      title: '酒店红木家具配套项目',
      alt: '酒店红木家具配套项目',
      content:
        '为一家五星级酒店提供了全套红木家具配套服务，包括客房家具、餐厅家具、大堂家具等。项目规模大，要求高，我们凭借丰富的经验和专业的团队，按时完成了所有任务，获得了客户的高度评价。',
      meta: JSON.stringify({
        client: '五星级酒店',
        category: '商业配套',
        date: '2024-08-10',
        tags: ['酒店配套', '商业空间', '大规模项目'],
      }),
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'case',
      groupKey: 'case_item',
      sortOrder: 3,
      title: '红木工艺品开发项目',
      alt: '红木工艺品开发项目',
      content:
        '与一家文化创意公司合作，开发了一系列具有文化内涵的红木工艺品。项目融合了传统工艺与现代设计，推出了多款深受市场欢迎的产品，为客户创造了良好的经济效益。',
      meta: JSON.stringify({
        client: '文化创意公司',
        category: '工艺品开发',
        date: '2024-07-05',
        tags: ['工艺品开发', '文化创意', '设计创新'],
      }),
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'case',
      groupKey: 'case_item',
      sortOrder: 4,
      title: '红木家具展览策划',
      alt: '红木家具展览策划',
      content:
        '为家具协会策划了一场红木家具展览，展示了来自全国各地的优质红木家具产品。展览吸引了大量观众和媒体关注，提升了红木家具的知名度和影响力。',
      meta: JSON.stringify({
        client: '家具协会',
        category: '展览策划',
        date: '2024-06-15',
        tags: ['展览策划', '行业活动', '品牌推广'],
      }),
      withImage: true,
      videoUrl: null,
    },
    {
      page: 'layout',
      groupKey: 'header',
      sortOrder: 0,
      title: null,
      alt: 'Logo',
      withImage: true,
      videoUrl: null,
    },
  ];

  for (const row of items) {
    await prisma.siteAsset.create({
      data: {
        page: row.page,
        groupKey: row.groupKey,
        sortOrder: row.sortOrder,
        title: row.title,
        alt: row.alt,
        content: row.content ?? null,
        meta: row.meta ?? null,
        videoUrl: row.videoUrl,
        image: row.withImage
          ? Buffer.from(imageBuffers[imgIdx++ % imageBuffers.length]!)
          : null,
      },
    });
  }

  console.log(`SiteAsset seed: ${items.length} rows`);
}
